### ISSUE TITLE
Set brightness on login screen failed

### ISSUE THREAD

**Issue by mosdeo** [Redsandro/thinkpad-x1-yoga#3]
Ubuntu 16.04, X1Y2 OLED  

/tmp/thinkpad-x1-yoga$ sudo env ANSIBLE_NOCOWS=1 ansible-playbook x1yoga.yml --skip-tags packages
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] *********************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************
ok: [localhost]

TASK [display : include_tasks] *******************************************************************************************************************************************************
included: /tmp/thinkpad-x1-yoga/roles/display/tasks/lightdm.yml for localhost
included: /tmp/thinkpad-x1-yoga/roles/display/tasks/oled-brightness.yml for localhost

TASK [display : Set login screen to HiDPI mode] **************************************************************************************************************************************
skipping: [localhost] => (item={u'key': u'xft-dpi', u'value': u'192'}) 

TASK [display : Set brightness on login screen] **************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "d8bb9152b6c0b0c4ad6a463348eafffb0861aade", "msg": "Destination directory /opt/etc does not exist"}
	to retry, use: --limit @/tmp/thinkpad-x1-yoga/x1yoga.retry

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1

**Comment by Nicceboy** [comment]
Ubuntu 18.04 XiY2 OLED, same problem here.

```shell
TASK [display : Set brightness on login screen] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "d8bb9152b6c0b0c4ad6a463348eafffb0861aade", "msg": "Destination directory /opt/etc does not exist"}
	to retry, use: --limit @/tmp/thinkpad-x1-yoga/x1yoga.retry
```

**Comment by Redsandro** [comment]
I don't have this laptop at the moment so I cannot test, but I think the directory needed to be created, so I created a possible fix on the `development` (!) branch: https://github.com/Redsandro/thinkpad-x1-yoga/commit/594349440367edd306fe2918df7d5e9ce1e4484b

Note that this was made for lightdm. I am not sure the new releases (Ubuntu 18, Linux Mint 19) can still use this.

Feel free to submit a tested+working PR, if this one doesn't fix the issue.

**Comment by Nicceboy** [comment]
Looks like that was the problem. It's depending on folders what already exists, and Ubuntu is missing some. Startup is handled by lightdm as well. If I have some time, i could make working version for Gnome.
